config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup',     to: 'users#new'

  resources :users, except: :new
  resources :people, except: [:index] do
    resources :phone_numbers, except: [:index, :show]
    resources :emails, except: [:index, :show]
    resources :addresses, except: [:index, :show]
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_many :phone_numbers, dependent: :destroy
  has_many :emails, dependent: :destroy
  has_many :addresses, dependent: :destroy

  default_scope -> { order(:first_name) }

  before_save :nameify

  validates :first_name, presence: true,
                         length: {minimum: 3, maximum: 50},
                         format: {with: /\A[a-zA-Z]+\z/,
                                  message: "Only allows letters"}
  validates :last_name, presence: true,
                        length: {minimum: 3, maximum: 50},
                        format: {with: /\A[a-zA-Z]+\z/,
                                 message: "Only allows letters"},
                        allow_blank: true

  validates :user_id, presence: true

  private

    def nameify
      self.first_name = self.first_name.downcase.capitalize
      self.last_name = self.last_name.downcase.capitalize
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :logged_in_user
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :find_person, only: [:show, :edit, :update, :destroy]

  def show

  end

  def new
    @person = Person.new
  end

  def create
    @user = current_user
    @person = @user.people.build(person_params)
    @phone_number = @person.phone_numbers.build(phone_number_params) unless @phone_number.blank?
    @email = @person.emails.build(email_params) unless @email.blank?
    if @person.save
      flash[:success] = "New contact created successfully."
      redirect_to root_path
    else
      # Errors handled by error_messages.html.erb partial
      render 'new'
    end
  end

  def edit

  end

  def update
    if @person.update_attributes(person_params)
      flash[:success] = "Contact updated successfully."
      redirect_to @person
    else
      # Errors handled by error_messages.html.erb partial
      render 'edit'
    end

  end

  def destroy
    @person.destroy
    flash[:success] = "#{@person.first_name} #{@person.last_name} deleted."
    redirect_to root_path
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name)
  end

  def phone_number_params
    params.require(:phone_numbers).permit(:number)
  end

  def email_params
    params.require(:emails).permit(:email)
  end

  # Before action

  def correct_user
    @person = Person.find(params[:id])
    unless current_user.id == @person.user_id
      flash[:danger] = "#{@person.fist_name} doesn't belong to you"
      redirect_to root_path
    end
  end

  def find_person
    @person = Person.find(params[:id])
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_person_form.html.erb
<%= form_for(@person) do |f|  %>

  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control" %>


  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %>

  <%= fields_for :phone_numbers do |p| %>
    <%= p.label :number %>
    <%= p.text_field :number, class: "form-control" %>
  <% end %>

  <%= fields_for :emails do |e| %>
    <%= e.label :email %>
    <%= e.text_field :email, class: "form-control" %>
  <% end %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

<%= link_to "<< Back", root_path %>

app/views/people/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Edit Contact</h1>

<%= form_for(@person) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control" %>


  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %>

  <%= f.submit 'Edit', class: "btn btn-primary" %>
<% end %>

<%= link_to "<< Back", root_path %>

app/views/people/index.html.erb
<% provide(:title, "Index") %>
<h1>Contacts</h1>

<ul>
  <% @people.each do |person| %>
    <li><%= person.first_name %>
        <%= person.last_name %>
        <%= link_to "show", person_path(person.id) %>
  <% end %>
</ul>

<p>Create new contact <%= link_to "here.", new_person_path %></p>

app/views/people/new.html.erb
<% provide(:title, "New Contact") %>
<%= provide(:button_text, "Add") %>
<h1>New Contact</h1>

<%= render 'person_form' %>

app/views/people/show.html.erb
<% provide(:title, @person.first_name) %>


<h2><%="#{@person.first_name} #{@person.last_name}" %></h2>
<p><%= link_to "Edit Contact", edit_person_path(@person.id)%>
   <%= link_to "Delete Contact", @person, method: :delete,
                                          data: {confirm: "Are you sure?"} %></p>


<div class="col-md-4">
  <p> Phone <%= "number".pluralize(@person.phone_numbers.count) %>:</p>
  <ul>
    <% @person.phone_numbers.each do |phone| %>
      <li><%= "#{phone.number}" %>
        <%= link_to "Edit", edit_person_phone_number_path(@person.id, phone.id) %>
        <%= link_to "Delete", person_phone_number_path(@person.id, phone.id),
                                     method: :delete,
                                     data: {confirm: "Are you sure"} %>
      </li>
      <% end %>
  </ul>
  <p><%= link_to "Add phone number", new_person_phone_number_path(@person.id) %></p>
</div>

<div class="col-md-4">
  <p><%= "Email".pluralize(@person.phone_numbers.count) %>:</p>
  <ul>
    <% @person.emails.each do |email| %>
      <li><%= "#{email.email}" %>
        <%= link_to "Edit", edit_person_email_path(@person.id, email.id) %>
        <%= link_to "Delete", person_email_path(@person.id, email.id), method: :delete,
                                     data: {confirm: "Are you sure"} %>
      </li>
      <% end %>
  </ul>
  <p><%= link_to "Add email",  new_person_email_path(@person.id) %></p>
</div>

<div class="col-md-4">
  <p><%= "Address".pluralize(@person.addresses.count) %>:</p>
  <ul>
    <% @person.addresses.each do |address| %>
      <li><%= "#{address.address}" %></li>
      <li><%= "#{address.city}, #{address.postcode}" %></li>
      <li><%= "#{address.state}, #{address.country}" %></li>

      <%= link_to "Edit", edit_person_address_path(@person.id, address.id) %>
      <%= link_to "Delete", person_address_path(@person.id, address.id), method: :delete,
                                                                         data: {confirm: "Are you sure"} %>
      <br /><br />
    <% end %>

  </ul>
  <p><%= link_to "Add address",  new_person_address_path(@person.id) %></p>
</div>

<p><%= link_to "<< Back", root_path %></p>