config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup',     to: 'users#new'

  resources :users, except: :new
  resources :people, except: [:index] do
    resources :phone_numbers, except: [:index, :show]
    resources :emails, except: [:index, :show]
    resources :addresses, except: [:index, :show]
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
 <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand" href="/">ContactManager</a>
   </div>
   <ul class="nav navbar-nav navbar-right">
     <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", root_path %></li>
            <li><%= link_to "Add Contact", new_person_path %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
     <% else %>
       <li>
        <a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a>
       </li>
       <li>
         <a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a>
       </li>
      <% end %>
   </ul>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | ContactManager</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'layouts/navigation' %>

    <% flash.each do |message_type ,message| %>
     <div class="alert alert-<%=message_type %>"><%= message %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>